name: Build and Deploy to linode

on:
  workflow_dispatch:

jobs:
  build:
    name: Build step
    runs-on: ubuntu-latest
    env:
      SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: double checking pwd
        run: ls ${{ github.workspace }}
      - name: var sub in angular src
        run: |
         sed -i "s/\[secret\]/'$SPOONACULAR_API_KEY/g" './rebornRecipes/ClientApp/src/environments/environment.ts'
         sed -i "s/[secret]/$SPOONACULAR_API_KEY/g" './rebornRecipes/ClientApp/src/environments/environment.prod.ts'
         cat ./rebornRecipes/ClientApp/src/environments/environment.ts
    #  - name: Restore dependencies
     #   run: dotnet restore
      #- name: Create Production Build
       # run: dotnet publish -c Release --no-restore
      #-  name: var sub in .net published
      #  uses: microsoft/variable-substitution@v1
       # with:
        #  files: './rebornRecipes/published/appsettings*.json'
       # env:
        #  ApplicationDbContext: ${{ secrets.APP_DB_CONTEXT }}
        
